version: '3'
services:

  nginx:
    image: tonyyb/laravel-nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "8043:443"
    volumes:
      - ./:/var/www
    networks:
      - app-network
    depends_on:
      - php-fpm

  php-fpm:
    image: tonyyb/laravel-php:latest
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
    networks:
      - app-network
    environment:
      APP_ENV: "production"
      APP_DEBUG: "false"
      DB_CONNECTION: "mysql"
      DB_HOST: "192.168.1.182"  # Your host machine's IP address
      DB_PORT: "3306"
      DB_DATABASE: "pos"
      DB_USERNAME: "root"
      DB_PASSWORD: "thz123456"

networks:
  app-network:
    driver: bridge


#   mysql:
#     image: mysql:5.7
#     restart: unless-stopped
#     tty: true
#     ports:
#       - "8006:3306"
#     volumes:
#       - mysqldata:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_USER: ${MYSQL_USER}
#       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#     networks:
#       - app-network

